// packages/angular/src/timeline.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  NgZone,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core';
import {
  Timeline as CoreTimeline,
  type Era,
  type PlayOptions,
  type Theme,
  type TimelineEvent,
  type TimelineGroup,
  type ViewRange,
} from '@openhistorymap/timeline-core';

/**
 * Angular binding for the OpenHistoryMap deep-time timeline.
 *
 * ```html
 * <timelin-timeline
 *   [(year)]="year"
 *   [events]="events"
 *   (eventSelect)="open($event)">
 * </timelin-timeline>
 * ```
 *
 * The `[(year)]` two-way binding pairs the `year` input with the `yearChange`
 * output. The component runs the core outside Angular's zone (it does its own
 * rendering) and only re-enters the zone to emit outputs.
 */
@Component({
  selector: 'timelin-timeline',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  template: `<div #host class="timelin-host"></div>`,
  styles: [
    `:host { display: block; width: 100%; height: var(--timelin-height, 120px); }
     .timelin-host { width: 100%; height: 100%; }`,
  ],
})
export class TimelinTimelineComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() year = 866;
  @Input() events: TimelineEvent[] = [];
  @Input() groups?: TimelineGroup[];
  @Input() groupMode?: 'auto' | 'swimlane' | 'flat';
  @Input() autoHeight = true;
  @Input() maxHeight?: number;
  @Input() groupGutter?: number;
  @Input() eras?: Era[];
  @Input() viewSpan?: number;
  @Input() theme?: Partial<Theme>;
  @Input() minSpan?: number;
  @Input() maxSpan?: number;
  @Input() animate = true;
  @Input() seekOnEventClick = true;

  @Output() yearChange = new EventEmitter<number>();
  @Output() rangeChange = new EventEmitter<ViewRange>();
  @Output() eraSelect = new EventEmitter<Era>();
  @Output() eventSelect = new EventEmitter<TimelineEvent>();
  @Output() groupSelect = new EventEmitter<TimelineGroup>();
  @Output() playing = new EventEmitter<boolean>();

  @ViewChild('host', { static: true }) hostRef!: ElementRef<HTMLDivElement>;

  private tl?: CoreTimeline;
  private lastEmittedYear = NaN;

  constructor(private zone: NgZone) {}

  ngAfterViewInit(): void {
    this.zone.runOutsideAngular(() => {
      this.tl = new CoreTimeline(this.hostRef.nativeElement, {
        year: this.year,
        events: this.events,
        groups: this.groups,
        groupMode: this.groupMode,
        autoHeight: this.autoHeight,
        maxHeight: this.maxHeight,
        groupGutter: this.groupGutter,
        eras: this.eras,
        viewSpan: this.viewSpan,
        theme: this.theme,
        minSpan: this.minSpan,
        maxSpan: this.maxSpan,
        animate: this.animate,
        seekOnEventClick: this.seekOnEventClick,
      });

      this.tl.on('yearChange', (y) =>
        this.zone.run(() => {
          this.lastEmittedYear = y;
          this.yearChange.emit(y);
        }),
      );
      this.tl.on('rangeChange', (r) => this.zone.run(() => this.rangeChange.emit(r)));
      this.tl.on('eraSelect', (e) => this.zone.run(() => this.eraSelect.emit(e)));
      this.tl.on('eventSelect', (e) => this.zone.run(() => this.eventSelect.emit(e)));
      this.tl.on('groupSelect', (g) => this.zone.run(() => this.groupSelect.emit(g)));
      this.tl.on('play', () => this.zone.run(() => this.playing.emit(true)));
      this.tl.on('pause', () => this.zone.run(() => this.playing.emit(false)));
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.tl) return;
    if (changes['year'] && Math.abs(this.year - this.lastEmittedYear) > 0.0001) {
      this.tl.setYear(this.year, { silent: true });
    }
    if (changes['events'] && this.events) this.tl.setEvents(this.events);
    if (changes['groups'] && this.groups) this.tl.setGroups(this.groups);
    if (changes['maxHeight']) this.tl.setMaxHeight(this.maxHeight);
    if (changes['eras'] && this.eras) this.tl.setEras(this.eras);
    if (changes['theme'] && this.theme) this.tl.setTheme(this.theme);
  }

  ngOnDestroy(): void {
    this.tl?.destroy();
  }

  /** Start playback. */
  play(opts?: PlayOptions): void {
    this.tl?.play(opts);
  }

  /** Stop playback. */
  pause(): void {
    this.tl?.pause();
  }

  /** Underlying core instance (escape hatch). */
  get instance(): CoreTimeline | undefined {
    return this.tl;
  }
}

// packages/react/src/Timeline.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
} from 'react';
import {
  Timeline as CoreTimeline,
  type Era,
  type PlayOptions,
  type Theme,
  type TimelineEvent,
  type TimelineGroup,
  type TimelineOptions,
  type ViewRange,
} from '@openhistorymap/timeline-core';

export interface TimelineProps {
  /** Controlled cursor year. Changes animate the cursor. */
  year?: number;
  /** Events to render in the event band. */
  events?: TimelineEvent[];
  /** Swimlane definitions (tag events via `event.group`). */
  groups?: TimelineGroup[];
  /** Layout mode: `'auto'` (default), `'swimlane'`, or `'flat'`. */
  groupMode?: 'auto' | 'swimlane' | 'flat';
  /** Grow height to fit swimlanes. Default true. */
  autoHeight?: boolean;
  /** Cap rendered height (px); taller lanes scroll vertically with a pinned axis. */
  maxHeight?: number;
  /** Left label gutter width (px) in swimlane mode. Default 132. */
  groupGutter?: number;
  /** Curated era markers (defaults to the bundled OHM set). */
  eras?: Era[];
  /** Initial visible span in years (used only on first mount). */
  viewSpan?: number;
  /** Design-token overrides. */
  theme?: Partial<Theme>;
  /** Zoom clamps. */
  minSpan?: number;
  maxSpan?: number;
  /** Animate cursor on `year` changes. Default true. */
  animate?: boolean;
  /** Seek to an event's year when it is clicked. Default true. */
  seekOnEventClick?: boolean;

  onYearChange?: (year: number) => void;
  onRangeChange?: (range: ViewRange) => void;
  onEraSelect?: (era: Era) => void;
  onEventSelect?: (event: TimelineEvent) => void;
  onGroupSelect?: (group: TimelineGroup) => void;
  onPlay?: () => void;
  onPause?: () => void;

  className?: string;
  style?: CSSProperties;
}

/** Imperative handle exposed via `ref`. */
export interface TimelineHandle {
  play(opts?: PlayOptions): void;
  pause(): void;
  setView(start: number, end: number): void;
  centerOn(year: number, span?: number): void;
  getYear(): number;
  /** Escape hatch to the underlying core instance. */
  readonly instance: CoreTimeline | null;
}

/**
 * React binding for `@openhistorymap/timeline-core`. The component owns a single
 * core instance for its lifetime; props are synced imperatively so React never
 * re-creates the timeline.
 */
export const Timeline = forwardRef<TimelineHandle, TimelineProps>(function Timeline(props, ref) {
  const hostRef = useRef<HTMLDivElement>(null);
  const coreRef = useRef<CoreTimeline | null>(null);

  // Keep latest callbacks in a ref so the subscription effect runs once.
  const cbRef = useRef(props);
  cbRef.current = props;

  /* Create the core once. */
  useEffect(() => {
    if (!hostRef.current) return;
    const opts: TimelineOptions = {
      year: cbRef.current.year,
      events: cbRef.current.events,
      groups: cbRef.current.groups,
      groupMode: cbRef.current.groupMode,
      autoHeight: cbRef.current.autoHeight,
      maxHeight: cbRef.current.maxHeight,
      groupGutter: cbRef.current.groupGutter,
      eras: cbRef.current.eras,
      viewSpan: cbRef.current.viewSpan,
      theme: cbRef.current.theme,
      minSpan: cbRef.current.minSpan,
      maxSpan: cbRef.current.maxSpan,
      animate: cbRef.current.animate,
      seekOnEventClick: cbRef.current.seekOnEventClick,
    };
    const tl = new CoreTimeline(hostRef.current, opts);
    coreRef.current = tl;

    const offs = [
      tl.on('yearChange', (y) => cbRef.current.onYearChange?.(y)),
      tl.on('rangeChange', (r) => cbRef.current.onRangeChange?.(r)),
      tl.on('eraSelect', (e) => cbRef.current.onEraSelect?.(e)),
      tl.on('eventSelect', (e) => cbRef.current.onEventSelect?.(e)),
      tl.on('groupSelect', (g) => cbRef.current.onGroupSelect?.(g)),
      tl.on('play', () => cbRef.current.onPlay?.()),
      tl.on('pause', () => cbRef.current.onPause?.()),
    ];

    return () => {
      offs.forEach((off) => off());
      tl.destroy();
      coreRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /* Sync controlled props. */
  useEffect(() => {
    if (props.year !== undefined) coreRef.current?.setYear(props.year, { silent: true });
  }, [props.year]);

  useEffect(() => {
    if (props.events) coreRef.current?.setEvents(props.events);
  }, [props.events]);

  useEffect(() => {
    if (props.groups) coreRef.current?.setGroups(props.groups);
  }, [props.groups]);

  useEffect(() => {
    if (props.eras) coreRef.current?.setEras(props.eras);
  }, [props.eras]);

  useEffect(() => {
    if (props.theme) coreRef.current?.setTheme(props.theme);
  }, [props.theme]);

  useEffect(() => {
    coreRef.current?.setMaxHeight(props.maxHeight);
  }, [props.maxHeight]);

  useImperativeHandle(
    ref,
    (): TimelineHandle => ({
      play: (opts) => coreRef.current?.play(opts),
      pause: () => coreRef.current?.pause(),
      setView: (s, e) => coreRef.current?.setView(s, e),
      centerOn: (y, span) => coreRef.current?.centerOn(y, span),
      getYear: () => coreRef.current?.getYear() ?? 0,
      get instance() {
        return coreRef.current;
      },
    }),
    [],
  );

  return <div ref={hostRef} className={props.className} style={props.style} />;
});
